### ISSUE TITLE
shouldnt we call dispose method on reload?

### ISSUE THREAD

**Issue by srghma** [nonbili/purescript-halogen-hmr-example#1]
here 

https://github.com/nonbili/purescript-halogen-hmr-example/blob/5083d55134462ecd477badb97417baa406553c7f/src/index.js#L9

```
import Main from "Main";
import "./Storybook.css";

if (process.env.NODE_ENV !== "production") {
  require("Main").main();

  if (module.hot) {
    module.hot.accept("Main", function() {
      document.body.innerHTML = "";
      require("Main").main();
    });
  }
}
```

should be written as

```
import Main from "Main";
import "./Storybook.css";

if (process.env.NODE_ENV !== "production") {
  let disposeFn = require("Main").main()

  if (module.hot) {
    module.hot.accept("Main", function() {
      disposeFn();
      document.body.innerHTML = "";
      disposeFn = require("Main").main();
    });
  }
}
```

of course `main` should return `Effect (Effect Unit)`

https://github.com/nonbili/purescript-halogen-hmr-example/blob/master/src/Main.purs#L22

https://github.com/purescript-halogen/purescript-halogen/blob/337d450fdd5e18de6f75920f808c34a173ff8d88/src/Halogen.purs#L35

**Comment by srghma** [comment]
other example - https://github.com/qwaneu/purescript-halogen-template/blob/master/entry.js

https://github.com/justinwoo/halogen-parcel-hot-reload-demo/blob/master/src/Main.js - (video https://twitter.com/jusrin00/status/985481356380696576, used to preserve state)

N.B.

good examples of middlewares

https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/example/server.js

https://github.com/alexmingoia/pux-starter-app/blob/isomorphic/support/client.entry.js

**Comment by rnons** [comment]
I think you're right, `dispose` should be called when reloading, do you want to send a PR or something.

**Comment by srghma** [comment]
> I think you're right, `dispose` should be called when reloading, do you want to send a PR or something.

dont want to make pr)

I implemented it in my project

https://github.com/srghma/purescript-halogen-material-components-web/blob/a67e38bb3dc90956ae74252fd69be0701fc8ab60/docs-src/Main.purs#L30

https://github.com/srghma/purescript-halogen-material-components-web/blob/a67e38bb3dc90956ae74252fd69be0701fc8ab60/docs-src/Main.js#L1-L23

https://github.com/srghma/purescript-halogen-material-components-web/blob/a67e38bb3dc90956ae74252fd69be0701fc8ab60/docs-src/index.js#L5-L26

**Comment by rnons** [comment]
Thanks for letting me know. Seems to me you don't need to use FFI to set the `dispose` function onto the `window`. As you said, just changing `main` to return `Effect (Effect Unit)`, please take a look at https://github.com/nonbili/purescript-halogen-hmr-example/commit/61f314017921a8ee7345507c72c18d5722f19584

BTW, I'm curious what problem do you see when using `document.body.innerHTML = "";` only

**Comment by srghma** [comment]
very good, I have updated my example with some changes https://github.com/srghma/purescript-halogen-material-components-web/commit/2c2d0d2355a8478d76605ba1cb3d829c44805108

> BTW, I'm curious what problem do you see when using `document.body.innerHTML = "";` only

isn't code of prev application is still running in that case?
I didn't check
